media:
  - name: docs
    label: Documents
    input: static/docs
    output: /static/docs
    categories: [document,spreadsheet]
content:
  - name: pages
    label: Pages
    type: collection
    path: content
    filename: "{primary}.md"
    format: toml-frontmatter
    fields:
      - name: title
        type: string
      - name: type
        type: select
        options:
          values: [default, chapter]
      - name: body
        type: rich-text
  - name: prompts
    label: Prompts
    type: file
    path: prompts.md